// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentsMicroService.Infrastructure.EF;

#nullable disable

namespace StudentsMicroService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230221221356_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("StudentsMicroService.Infrastructure.Entities.AcademicData", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Grade")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentId");

                    b.ToTable("AcademicData", (string)null);
                });

            modelBuilder.Entity("StudentsMicroService.Infrastructure.Entities.PersonalData", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("PersonalData", (string)null);
                });

            modelBuilder.Entity("StudentsMicroService.Infrastructure.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("StudentsMicroService.Infrastructure.Entities.AcademicData", b =>
                {
                    b.HasOne("StudentsMicroService.Infrastructure.Entities.Student", null)
                        .WithOne("AcademicData")
                        .HasForeignKey("StudentsMicroService.Infrastructure.Entities.AcademicData", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentsMicroService.Infrastructure.Entities.Student", b =>
                {
                    b.HasOne("StudentsMicroService.Infrastructure.Entities.PersonalData", "PersonalData")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalData");
                });

            modelBuilder.Entity("StudentsMicroService.Infrastructure.Entities.Student", b =>
                {
                    b.Navigation("AcademicData")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
